import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/shared/Navbar";
import { Sidebar } from "@/components/ui/sidebar";
import { SidebarDemo } from "./(root)/_components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      
    <div className="dark h-[100vh]">
      <Navbar/>
      <div className="flex h-full ">
      <SidebarDemo/>
      {children}
      </div>
      
    </div>
  
</>
  );
}
